DROP TABLE IF EXISTS TICKETS;

CREATE TABLE TICKETS (
  id VARCHAR(250) PRIMARY KEY,
  departure_date TIMESTAMP WITH TIME ZONE NOT NULL,
  arrival_date TIMESTAMP WITH TIME ZONE NOT NULL,
  origin VARCHAR(250) NOT NULL,
  destination VARCHAR(250) NOT NULL,
  passenger VARCHAR(250) NOT NULL,
  passenger_age INT NOT NULL,
  price VARCHAR(250) NOT NULL,
  luggage_hold BOOLEAN NOT NULL
);

